name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_cik:
        description: 'Masukkan nomor CIK (contoh: 0000320193)'
        required: false
        default: '0000320193'      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests -t .

    - name: Create Zip Bundle
      run: |
        cd src
        zip -r ../bundle.zip .

    - name: Deploy to Lambda
      uses: appleboy/lambda-action@v0.1.9
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1 
        function_name: lambda_ingest
        zip_file: bundle.zip

    - name: Invoke Lambda
      run: |
        aws lambda invoke \
          --function-name ${{ matrix.lambda }} \
          --payload '{}' response.json
        cat response.json
 
