name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_cik:
        description: 'Masukkan nomor CIK (contoh: 0000320193)'
        required: false
        default: '0000320193'   
  schedule:
    - cron: '0 0 * * 5'

jobs:
  bronze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t src/
        cd src
        zip -r ../bundle.zip .

    - name: Deploy to Lambda
      uses: appleboy/lambda-action@v0.1.9
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1 
        function_name: lambda_ingest
        zip_file: bundle.zip

    - name: Trigger Lambda Function
      run: |
        aws lambda invoke --function-name lambda_ingest --payload '{"cik": "0000320193"}' --cli-binary-format raw-in-base64-out response.json
        echo "--- Lambda Response ---"
        cat response.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1


  silver:

    needs: bronze
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install DuckDB CLI
        run: |

          wget https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          chmod +x ./duckdb


      - name: Run Casting & Transform
        env:
          motherduck_token: ${{ secrets.MD_TOKEN }}
        run: |
          for file in src/silver.sql; do
            ./duckdb md:my_db < "$file"
          done
